package com.fitz.abus;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.fitz.abus.Bean.BusLineBean;

import com.fitz.abus.BusLineBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig busLineBeanDaoConfig;

    private final BusLineBeanDao busLineBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        busLineBeanDaoConfig = daoConfigMap.get(BusLineBeanDao.class).clone();
        busLineBeanDaoConfig.initIdentityScope(type);

        busLineBeanDao = new BusLineBeanDao(busLineBeanDaoConfig, this);

        registerDao(BusLineBean.class, busLineBeanDao);
    }
    
    public void clear() {
        busLineBeanDaoConfig.clearIdentityScope();
    }

    public BusLineBeanDao getBusLineBeanDao() {
        return busLineBeanDao;
    }

}
