package com.fitz.abus.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.fitz.abus.bean.BusBaseInfoDB;

import com.fitz.abus.greendao.BusBaseInfoDBDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig busBaseInfoDBDaoConfig;

    private final BusBaseInfoDBDao busBaseInfoDBDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        busBaseInfoDBDaoConfig = daoConfigMap.get(BusBaseInfoDBDao.class).clone();
        busBaseInfoDBDaoConfig.initIdentityScope(type);

        busBaseInfoDBDao = new BusBaseInfoDBDao(busBaseInfoDBDaoConfig, this);

        registerDao(BusBaseInfoDB.class, busBaseInfoDBDao);
    }
    
    public void clear() {
        busBaseInfoDBDaoConfig.clearIdentityScope();
    }

    public BusBaseInfoDBDao getBusBaseInfoDBDao() {
        return busBaseInfoDBDao;
    }

}
