package com.fitz.abus.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.fitz.abus.bean.BusLineDB;

import com.fitz.abus.greendao.BusLineDBDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig busLineDBDaoConfig;

    private final BusLineDBDao busLineDBDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        busLineDBDaoConfig = daoConfigMap.get(BusLineDBDao.class).clone();
        busLineDBDaoConfig.initIdentityScope(type);

        busLineDBDao = new BusLineDBDao(busLineDBDaoConfig, this);

        registerDao(BusLineDB.class, busLineDBDao);
    }
    
    public void clear() {
        busLineDBDaoConfig.clearIdentityScope();
    }

    public BusLineDBDao getBusLineDBDao() {
        return busLineDBDao;
    }

}
