package com.wind.fitz.greendaodemo;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.wind.fitz.greendaodemo.bean.BusLine;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BUS_LINE".
*/
public class BusLineDao extends AbstractDao<BusLine, Long> {

    public static final String TABLENAME = "BUS_LINE";

    /**
     * Properties of entity BusLine.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property BusID = new Property(0, Long.class, "busID", true, "_id");
        public final static Property CityID = new Property(1, String.class, "cityID", false, "CITY_ID");
        public final static Property LineID = new Property(2, String.class, "lineID", false, "LINE_ID");
        public final static Property LineName = new Property(3, String.class, "lineName", false, "LINE_NAME");
        public final static Property StationID = new Property(4, int.class, "stationID", false, "STATION_ID");
        public final static Property StationName = new Property(5, String.class, "stationName", false, "STATION_NAME");
    }


    public BusLineDao(DaoConfig config) {
        super(config);
    }
    
    public BusLineDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BUS_LINE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: busID
                "\"CITY_ID\" TEXT NOT NULL ," + // 1: cityID
                "\"LINE_ID\" TEXT NOT NULL UNIQUE ," + // 2: lineID
                "\"LINE_NAME\" TEXT NOT NULL UNIQUE ," + // 3: lineName
                "\"STATION_ID\" INTEGER NOT NULL UNIQUE ," + // 4: stationID
                "\"STATION_NAME\" TEXT NOT NULL UNIQUE );"); // 5: stationName
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BUS_LINE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BusLine entity) {
        stmt.clearBindings();
 
        Long busID = entity.getBusID();
        if (busID != null) {
            stmt.bindLong(1, busID);
        }
        stmt.bindString(2, entity.getCityID());
        stmt.bindString(3, entity.getLineID());
        stmt.bindString(4, entity.getLineName());
        stmt.bindLong(5, entity.getStationID());
        stmt.bindString(6, entity.getStationName());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BusLine entity) {
        stmt.clearBindings();
 
        Long busID = entity.getBusID();
        if (busID != null) {
            stmt.bindLong(1, busID);
        }
        stmt.bindString(2, entity.getCityID());
        stmt.bindString(3, entity.getLineID());
        stmt.bindString(4, entity.getLineName());
        stmt.bindLong(5, entity.getStationID());
        stmt.bindString(6, entity.getStationName());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public BusLine readEntity(Cursor cursor, int offset) {
        BusLine entity = new BusLine( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // busID
            cursor.getString(offset + 1), // cityID
            cursor.getString(offset + 2), // lineID
            cursor.getString(offset + 3), // lineName
            cursor.getInt(offset + 4), // stationID
            cursor.getString(offset + 5) // stationName
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, BusLine entity, int offset) {
        entity.setBusID(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCityID(cursor.getString(offset + 1));
        entity.setLineID(cursor.getString(offset + 2));
        entity.setLineName(cursor.getString(offset + 3));
        entity.setStationID(cursor.getInt(offset + 4));
        entity.setStationName(cursor.getString(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(BusLine entity, long rowId) {
        entity.setBusID(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(BusLine entity) {
        if(entity != null) {
            return entity.getBusID();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(BusLine entity) {
        return entity.getBusID() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
