package com.wind.fitz.greendaodemo;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.wind.fitz.greendaodemo.bean.BusLine;

import com.wind.fitz.greendaodemo.BusLineDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig busLineDaoConfig;

    private final BusLineDao busLineDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        busLineDaoConfig = daoConfigMap.get(BusLineDao.class).clone();
        busLineDaoConfig.initIdentityScope(type);

        busLineDao = new BusLineDao(busLineDaoConfig, this);

        registerDao(BusLine.class, busLineDao);
    }
    
    public void clear() {
        busLineDaoConfig.clearIdentityScope();
    }

    public BusLineDao getBusLineDao() {
        return busLineDao;
    }

}
